import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Footer } from '../components/Footer'
import { Main } from '../components/Main'

export default function About(props) {
  // ファイルシステムルーティングを機能させるためにpages配下のファイルはexport defaultにしなければいけない。
  return (
    <div className={styles.container}>
      <Head>
        <title>About page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <main className={styles.main}>
        <Headline 
          page="about" 
          number={111} 
          array={[1, 2, 3]}
          obj={{foo:"foo", bar: "bar"}}
          boolean={true} // trueの場合は省略して「boolean」だけの記述でもtrueを返せる
        >
          <code className={styles.code}>pages/about.js</code>
          </Headline>
        <Links />
      </main> */}
      <Main page="about" />

      <Footer />
    </div>
  )
}
